language: r
warnings_are_errors: false
sudo: required
cache: packages

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.8
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - sudo apt-get install libgfortran3
  - sudo apt-get install r-base-dev
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libarmadillo2
  #- sudo apt-get install software-properties-common
  #- sudo add-apt-repository ppa:george-edison55/cmake-3.x -y -y -y -y -y
  #- sudo apt-get update
  #- sudo apt-get install cmake
  #- sudo apt-get upgrade -y -y -y -y -y
  - sudo apt-get update
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get update
  - sudo apt-get install libarpack++2-dev
  - sudo dpkg --purge gfortran
  - sudo apt-get install gfortran
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so

r_packages:
  - devtools
  - roxygen2
  - testthat
  - knitr
  - rmarkdown
  - Rcpp
  - RcppArmadillo
  - shiny
  - jpeg
  - png
  - tiff
  - covr


after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/RcppExports.R", "src/RcppExports.cpp"), quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
